#!/bin/sh /etc/rc.common

# rc.common consumes these variables after sourcing the file.
# shellcheck disable=SC2034
USE_PROCD=1
START=95
STOP=11

PROG="${NFQWS_BIN:-/usr/bin/nfqws}"
CONFIG="${ROUTER_POLICY_ZAPRET_CONFIG:-/etc/router-policy/zapret/nfqws.conf}"

start_service() {
	[ -x "$PROG" ] || return 1
	[ -s "$CONFIG" ] || return 1
	procd_open_instance router-policy-zapret
	procd_set_param command "$PROG" "@$CONFIG"
	procd_set_param file "$CONFIG"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

reload_service() {
	stop
	start
}
