#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034

START=96
STOP=9
USE_PROCD=1

start_service() {
  procd_open_instance router-policy-watchdog
	procd_set_param command /usr/bin/router-policy watchdog --health-url http://127.0.0.1:8787/api/v1/health --interval 60s --startup-grace 90s --failure-threshold 3 --inhibit-file /tmp/router-policy/watchdog-inhibit.json --service-script /etc/init.d/router-policy
  procd_set_param respawn 5 5 0
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
